server:
  port: 8001
spring:
  application:
    name: cloud-ShowIndex-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/restaurant?serverTimezone=Asia/Shanghai&userUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.itmao.restaurant.entities
