server:
  port: 8001
spring:
  application:
    name: cloud-ShowIndex-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/restaurant?serverTimezone=Asia/Shanghai&userUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
  redis:
    port: 6379
    host: localhost

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.itmao.restaurant.entities
eureka:
  instance:
    instance-id: showindex8001
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

